Correct log message when doing a restart; they said reload. Move the PostgreSQL restart to a reload. We don't want the DB restarting.

diff --git a/cert-puller b/cert-puller
--- a/cert-puller
+++ b/cert-puller
@@ -176,17 +176,17 @@ restart_services(){
         ${LOGGER} doing a graceful on ${service}
         ERRORS=`${SUDO} ${SERVICE} ${service} graceful 2>&1`
         if [ $? != 0 ]; then
-          ${LOGGER} ERROR on restart
+          ${LOGGER} ERROR on graceful
           ${LOGGER} "${ERRORS}"
           echo "${ERRORS}"
         else
-          ${LOGGER} no errors on restart
+          ${LOGGER} no errors on graceful
         fi
         ;;
 
       # it might be better if we do a reload.
       # will that be sufficient?
-      "dovecot" | "mosquitto" | "nginx" | "postfix" | "postgresql" )
+      "dovecot" | "mosquitto" | "nginx" | "postfix" )
         ${LOGGER} restarting ${service}
         ERRORS=`${SUDO} ${SERVICE} ${service} restart 2>&1`
         if [ $? != 0 ]; then
@@ -197,7 +197,20 @@ restart_services(){
           ${LOGGER} no errors on restart
         fi
         ;;
-      
+
+      # For Postgresql, we only do a reload
+      "postgresql" )
+        ${LOGGER} reloading ${service}
+        ERRORS=`${SUDO} ${SERVICE} ${service} reload 2>&1`
+        if [ $? != 0 ]; then
+          ${LOGGER} ERROR on reload
+          ${LOGGER} "${ERRORS}"
+          echo "${ERRORS}"
+        else
+          ${LOGGER} no errors on reload
+        fi
+        ;;
+
       *)
         ${LOGGER} "Unknown service requested in $0: ${service}"
         ;;
