When a fetch fails, log it.

diff --git a/cert-puller b/cert-puller
--- a/cert-puller
+++ b/cert-puller
@@ -94,6 +94,10 @@ fetch_new_certs(){
     do
       ${LOGGER}         "${cert} :: ${file}"
       ${FETCH} -o ${DOWNLOAD_DIR} ${CERT_SERVER}/${cert}/${file}
+      RESULT=$?
+      if [ "${RESULT}" != "0" ]; then
+        ${LOGGER} "error '${RESULT}' on fetch - perhaps the remote file does not exist."
+      fi
     done
   done
 }
